# Generated by Django 3.2.4 on 2021-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(default='No Image Provided', upload_to=''),
        ),
    ]
